### ISSUE TITLE
Don't show the about Icon in about page.

### ISSUE THREAD

**Issue by AhanafVai** [bradtraversy/feedback-app#11]
This will fix the issue

**Comment by levi-blodgett** [comment]
This doesn't really look like an issue, can you add more details or close this?

You said "This will fix the issue" but I also don't see anything around that.

**Comment by AhanafVai** [comment]
The about icon is a link to navigate from home to about. So when you are on the about page you do not have to show the about icon. It is not a major problem but it is better not to show the icon on the about page. I added a conditional to so that the about icon will show on the home page but not on the about page.
