### ISSUE TITLE
Failed to compile -  ./src/components/Header.jsx  

### ISSUE THREAD

**Issue by Shksantosh** [bradtraversy/feedback-app#12]
./src/components/Header.jsx  

 Line 11:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 12:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 13:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 14:  'React' must be in scope when using JSX  react/react-in-jsx-scope

Search for the keywords to learn more about each error.

**Comment by lukeryandev** [comment]
Did you import react using React (capital R?). Also, you can add the following to your .eslint

  rules: {
    // suppress errors for missing 'import React' in files
   "react/react-in-jsx-scope": "off",
    // allow jsx syntax in js files (for next.js project)
   "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }], //should add ".ts" if typescript project
  }

**Comment by levi-blodgett** [comment]
I think this could be closed, @lukeryandev answered above and it hasn't been active in over a month.

If you are able to do so, @Shksantosh.

**Comment by Shksantosh** [comment]
No its not working  I am  already used that in my file @lukeryandev but thanks for tips and i have solve that issue @levi-blodgett .
