### ISSUE TITLE
Uncaught Promise in 'main' code

### ISSUE THREAD

**Issue by lukeryandev** [bradtraversy/feedback-app#13]
Hey, I was following a tutorial specifically around the useContext but the edit functionality was returning an error, not filling the form. I forked from the main branch and ran the project but there was still an uncaught promise error: 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/75271909/202772780-c359ac74-994a-450f-89b7-41c4d7724ed0.png">

I assume it's around versioning but any support appreciated.

**Comment by codetipster** [comment]
From the error message, it appears you are trying to pass a JSON in the
wrong format.

Suggestion:
Try to console log whatever inputs you are trying to parse to be sure it's
in the right form.

**Comment by lukeryandev** [comment]
Thanks for the response, but I did already try that based on the text of the error message. I can't seem to find the location this is happening. As I mentioned in OP, this issue is with the courses 'main' code also. Simply forking, running npm i and npm start loads the application with bugs so was hoping Brad or his team could rectify the source code so I can compare against the error.

This is after a clean fork/install:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/75271909/203008495-e57a276f-4334-4856-bf4b-eb3f1efbfe8a.png">

**Comment by codetipster** [comment]
Okay! Did you configure your firebase?, it appears like the client server
connection to a backend server is broken.

**Comment by levi-blodgett** [comment]
@codetipster This project uses Netlify to host frontend and the backend is managed via JSON SERVER locally, it looks like based on the screenshot he is running it locally as well.

I forked and then git reset to commit b308a0b to test and still didn't get these errors @lukeryandev.

If you haven't, try:
- A clean fork on the most recent commit
- Clear the cache on localhost:3000
- Double-check nothing else is trying to run on port 3000 locally

If you still get the error, could you post a screenshot of the edit and update feedback functions as well as your proxy settings in package.json?

**Comment by bushblade** [comment]
Hi @lukeryandev 
Sorry for the late reply.
The issue is that you are not running json-server, so your client is not getting any response when making the request to json-server.
Make sure to run the server in one terminal
```sh
npm run server
```
And then in another terminal run the client React app..
```sh
npm start
```
Or use the dev script to run both scripts in one terminal process...
```sh
npm run dev
```
