### ISSUE TITLE
SetFeedbackEdit.edit to false 

### ISSUE THREAD

**Issue by nayabshah** [bradtraversy/feedback-app#3]
SetFeedback edit to false becouse after updating it will always on edit mood

**Comment by bushblade** [comment]
Hi @nayabshah 
Yeah a few other students have pointed this out.
Currently we are addressing issues and bugs with the course code on the [bugfix](https://github.com/bradtraversy/feedback-app/tree/bugfix#issues-found-so-far) branch of this repo. In the code there `feedbackEdit` state is reset after editing a feedback.
Hope that helps.
I'll close here for now as we have this one thanks.
