### ISSUE TITLE
"proxy": "http://localhost:5000",

### ISSUE THREAD

**Issue by llasszzll** [bradtraversy/feedback-app#7]
When trying to run a new terminal and _**
![errorReact2](https://user-images.githubusercontent.com/22605437/156884416-b200dfa4-fa62-43b8-a11c-4d755a06640e.JPG)
![errorReact](https://user-images.githubusercontent.com/22605437/156884413-097fa0f8-88f4-4ad3-b4e1-6ab5217277ba.JPG)**_ I receive the following error and the spinner just appears under the review submit box. Error receiving:

_Proxy error: Could not proxy request /sockjs-node/428/cjfr1prk/websocket from localhost:3001 to [http://localhost:5000/.](http://localhost:5000/)_

**Comment by bushblade** [comment]
Hi @llasszzll 
Is your json-server running?

**Comment by llasszzll** [comment]
Hi @bushblade

Json server running now. App build is complete. Thank you for checking in.
